version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.14.0

commands:
  restore_npm_cache:
    steps:
      - restore_cache:
          name: Restore cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  save_npm_cache:
    steps:
      - save_cache:
          name: Save cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - restore_npm_cache
      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - save_npm_cache
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - restore_npm_cache
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - add_ssh_keys:
          fingerprints:
            - "5e:08:6c:dd:81:96:84:8e:77:2f:7b:ac:c4:81:39:b6"
      - run: npm run generate:gh-pages
      - run: gh-pages -d repo/dist -m 'Update [skip ci]' -t

workflows:
  build-test-publish:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
